apiVersion: apps/v1
kind: Deployment

metadata:
  name: contact-management

spec:
  replicas: 1

  selector:
    matchLabels:
      app: contact-management

  template:
    metadata:
      labels:
        app: contact-management

    spec:
      containers:
        - name: contact-management
          image: ghcr.io/nitha-mathew/contact-management-devops:latest

          ports:
            - containerPort: 5001

          env:
            - name: DB_SERVER
              value: "mssql"

            - name: DB_NAME
              value: "DevOpsAI"

            - name: DB_USER
              value: "devops_app"

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-db-secret
                  key: DB_PASSWORD