name: Flask CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: 'Nithatemp@1234'
        ports:
          - 1433:1433

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Wait for SQL Server
        run: |
          echo "Waiting for SQL Server..."
          for i in {1..30}; do
            if timeout 2 bash -c '</dev/tcp/localhost/1433' 2>/dev/null; then
              echo "SQL Server port is ready."
              break
            fi
            echo "Waiting..."
            sleep 2
          done
      - name: Initialize SQL Server
        run: |
          docker run --rm \
            --network host \
            -v "${{ github.workspace }}/ci/init.sql:/init.sql" \
            mcr.microsoft.com/mssql-tools18 \
            /opt/mssql-tools18/bin/sqlcmd \
            -S localhost,1433 \
            -U sa \
            -P 'Nithatemp@1234' \
            -C \
            -i /init.sql

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build test Docker image
        run: docker build -t flask-test .

      - name: Run tests
        run: docker run --rm --add-host=host.docker.internal:host-gateway flask-test python -m pytest tests/test_app.py